
export type PlayableAdItem = {
    appName: string;
    playableName: string;
    /** Path under /public. A plain string on purpose: a static import inlines
     *  an unused ~400-byte blur placeholder per icon into the page bundle. */
    icon: string;
    url: string;
    isHighlighted: boolean;
};

export const playableAdsData: PlayableAdItem[] = [
    {
        appName: "Word Tiles",
        playableName: "Q-A Many Letters",
        icon: "/AppIcons/WT_Icon.png",
        url: "/playableAds/QAManyLetters_WordTiles_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Word Tiles",
        playableName: "Family Feud",
        icon: "/AppIcons/WT_Icon.png",
        url: "/playableAds/FamilyFeud_WordTiles_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Word Tiles",
        playableName: "No Break Many Words",
        icon: "/AppIcons/WT_Icon.png",
        url: "/playableAds/NoBreakManyWords_WordTiles_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Word Tiles",
        playableName: "Descending Square Words With Flexible Groups",
        icon: "/AppIcons/WT_Icon.png",
        url: "/playableAds/DescendingSquareWordsWFlexibleGroupSizes_WordTiles_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Find Em All",
        playableName: "Search It Multiple Collections",
        icon: "/AppIcons/FindEmAllLogo.png",
        url: "/playableAds/SearchItMultipleCollection_FindEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Find Em All",
        playableName: "Find Multiple Same Objects",
        icon: "/AppIcons/FindEmAllLogo.png",
        url: "/playableAds/FindMultipleSameObjects_FindEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Hidden Match",
        playableName: "Base Gameplay- Level 44",
        icon: "/AppIcons/hiddenMatchIcon.png",
        url: "/playableAds/BaseGameplay-Level44_HiddenMatch_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Math Logic Puzzle",
        playableName: "Base Gameplay",
        icon: "/AppIcons/mathLogicPuzzleIcon.png",
        url: "/playableAds/BaseGameplay_MathLogicPuzzle_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Find Em All",
        playableName: "ZoomPanCollectOnUI-Level323",
        icon: "/AppIcons/FindEmAllLogo.png",
        url: "/playableAds/ZoomPanCollectOnUI-Level323_FindEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Find Em All",
        playableName: "BreakableOpenCenterTiles Level35",
        icon: "/AppIcons/FindEmAllLogo.png",
        url: "/playableAds/BreakableOpenCenter52TilesLevel35_FindEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Word Tiles",
        playableName: "Descending Square Words",
        icon: "/AppIcons/WT_Icon.png",
        url: "/playableAds/DescendingSquareWords_WordTiles_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true
    },
    {
        appName: "Word Tiles",
        playableName: "Base Gameplay 3x3 - 3 Levels",
        icon: "/AppIcons/WT_Icon.png",
        url: "/playableAds/BaseGameplay3x3-3Levels_WordTiles_Responsive_Playable_01_Unity_ALL.html", // DescendingSquareWords
        isHighlighted: true
    },
    {
        appName: "Cat Logic Puzzle",
        playableName: "Base Gameplay",
        icon: "/AppIcons/CLP_Icon.png",
        url: "/playableAds/BaseGameplay_CatLogicPuzzle_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Cat Logic Puzzle",
        playableName: "Spotlight And No Fail",
        icon: "/AppIcons/CLP_Icon.png",
        url: "/playableAds/SpotlightAndNoFail_CatLogicPuzzle_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Find Em All",
        playableName: "Find A Like Level101",
        icon: "/AppIcons/FindEmAllLogo.png",
        url: "/playableAds/FindALikeLevel101_FindEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Find The Cat 2",
        playableName: "Breakable Ascending Tile Clear",
        icon: "/AppIcons/FindTheCat2Logo.png",
        url: "/playableAds/BreakableAscendingTileClear_FindTheCat2_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Art Block Puzzle",
        playableName: "Multiple Levels",
        icon: "/AppIcons/ArtBlockPuzzleLogo.png",
        url: "/playableAds/MultipleLevels_ArtBlockPuzzle_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Find Em All",
        playableName: "Multiple Levels Collect On Scrollable UI",
        icon: "/AppIcons/FindEmAllLogo.png",
        url: "/playableAds/MultipleLevelsCollectOnScrollableUI_FindEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Find The Cat 2",
        playableName: "Zoom Pan UI Collect - LvL 1616",
        icon: "/AppIcons/FindTheCat2Logo.png",
        url: "/playableAds/ZoomPanUICollect-LvL1616_FindTheCat2_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Find Em All",
        playableName: "Multiple Category Collect",
        icon: "/AppIcons/FindEmAllLogo.png",
        url: "/playableAds/MultipleCategoryCollectLevel35_FindEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Art Block Puzzle",
        playableName: "Step Zoom Out",
        icon: "/AppIcons/ArtBlockPuzzleLogo.png",
        url: "/playableAds/StepZoomOut_ArtBlockPuzzle_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    // {
    //     appName: "Find The Cat",
    //     playableName: "MultiLevel",
    //     icon: "/AppIcons/FindTheCat.png",
    //     url: "/playableAds/MultiLevel_FindTheCat_Responsive_Playable_01_Unity_ALL.html",
    //     isHighlighted: false,
    // },
    {
        appName: "Find Em All",
        playableName: "AscendingTileClear - Lvl 11",
        icon: "/AppIcons/FindEmAllLogo.png",
        url: "/playableAds/AscendingTileClearLevel11_FindEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    // {
    //     appName: "Find The Cat",
    //     playableName: "ScrollableCollectOnUI",
    //     icon: "/AppIcons/FindTheCat.png",
    //     url: "/playableAds/ScrollableCollectOnUI_FindTheCat_Responsive_Playable_01_Unity_ALL.html",
    //     isHighlighted: true,
    // },
    {
        appName: "Find The Cat",
        playableName: "StaticCollectOnUI",
        icon: "/AppIcons/FindTheCat.png",
        url: "/playableAds/StaticCollectOnUI_FindTheCat_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Art Block Puzzle",
        playableName: "Pyramid",
        icon: "/AppIcons/ArtBlockPuzzleLogo.png",
        url: "/playableAds/Pyramid_ArtBlockPuzzle_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Find The Cat",
        playableName: "Newspaper - Water Paint",
        icon: "/AppIcons/FindTheCat.png",
        url: "/playableAds/WaterPaint_FindTheCat_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Soda Match",
        playableName: "Cocktails - Carousel Scroll",
        icon: "/AppIcons/SodaSort.png",
        url: "/playableAds/Cocktails-CarouselScroll_SodaMatch_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Soda Match",
        playableName: "Cocktails - Horizontal Scroll",
        icon: "/AppIcons/SodaSort.png",
        url: "/playableAds/Cocktails-HorizontalScroll_SodaMatch_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Soda Match",
        playableName: "Cocktails - 3 Renewable",
        icon: "/AppIcons/SodaSort.png",
        url: "/playableAds/Cocktails-3Renewable_SodaMatch_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Soda Match",
        playableName: "Cocktails - 1 Renewable",
        icon: "/AppIcons/SodaSort.png",
        url: "/playableAds/Cocktails-1Renewable_SodaMatch_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Soda Match",
        playableName: "Cocktails - 3 Static",
        icon: "/AppIcons/SodaSort.png",
        url: "/playableAds/Cocktails-3Static_SodaMatch_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Soda Match",
        playableName: "Branch Bottle",
        icon: "/AppIcons/SodaSort.png",
        url: "/playableAds/BranchBottle_SodaMatch_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Soda Match",
        playableName: "Long Strawberry Bottle",
        icon: "/AppIcons/SodaSort.png",
        url: "/playableAds/LongStrawberryBottle_SodaMatch_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Find The Cat",
        playableName: "Zoom& Pan - WhaleLevel",
        icon: "/AppIcons/FindTheCat2Logo.png",
        url: "/playableAds/Zoom&PanWhaleLevel_FindTheCat_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Find The Cat 2",
        playableName: "Zoom& Pan& Collect To UI",
        icon: "/AppIcons/FindTheCat2Logo.png",
        url: "/playableAds/Zoom&Pan&CollectToUI_FindTheCat2_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Find Em All",
        playableName: "Collect Scroll Area - Lvl 26",
        icon: "/AppIcons/FindEmAllLogo.png",
        url: "/playableAds/CollectOnScrollAreaLevel26_FindEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Find The Cat",
        playableName: "Base Game Play-Level 622",
        icon: "/AppIcons/FindTheCat.png",
        url: "/playableAds/BaseGamePlay-Level622_FindTheCat_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Find The Cat 2",
        playableName: "Collect On Score UI",
        icon: "/AppIcons/FindTheCat2Logo.png",
        url: "/playableAds/CollectOnScoreUI_FindTheCat2_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Art Block Puzzle",
        playableName: "Flip Card",
        icon: "/AppIcons/ArtBlockPuzzleLogo.png",
        url: "/playableAds/FlipCard_ArtBlockPuzzle_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Find The Cat",
        playableName: "Find The Selected Animal",
        icon: "/AppIcons/FindTheCat.png",
        url: "/playableAds/FindTheSelectedAnimal_FindTheCat_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Find The Cat",
        playableName: "CountAndPickAnswer",
        icon: "/AppIcons/FindTheCat.png",
        url: "/playableAds/CountAndPickAnswer_FindTheCat_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Art Block Puzzle",
        playableName: "Puzzle",
        icon: "/AppIcons/ArtBlockPuzzleLogo.png",
        url: "/playableAds/Puzzle_ArtBlockPuzzle_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Find The Cat",
        playableName: "Survey",
        icon: "/AppIcons/FindTheCat.png",
        url: "/playableAds/Survey_FindTheCat_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Cash Giraffe",
        playableName: "Google - Color Tiles",
        icon: "/AppIcons/colorTilesLogo.png",
        url: "/playableAds/ColorTiles_CashGiraffe_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Cash Giraffe",
        playableName: "Ball Blast",
        icon: "/AppIcons/BallBlast.png",
        url: "/playableAds/BallBlast_CashGiraffe_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Cash Clash",
        playableName: "Ninja Jump",
        icon: "/AppIcons/NinjaJump.png",
        url: "/playableAds/NinjaJump_CashClash_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Soda Sort",
        playableName: "Agave Games",
        icon: "/AppIcons/SodaSort.png",
        url: "/playableAds/SodaSort_AgaveGames_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Money Well",
        playableName: "Bundes Bank",
        icon: "/AppIcons/BundesBank.jpg",
        url: "/playableAds/BundesBank_MoneyWell_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Cash Giraffe",
        playableName: "2 The Moon",
        icon: "/AppIcons/ToTheMoonLogo.png",
        url: "/playableAds/ToTheMoon_CashGiraffe_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Play Zone",
        playableName: "Block Jam 3D: Color Puzzle",
        icon: "/AppIcons/blockJam3D-ColorPuzzle.png",
        url: "/playableAds/BlockJam3D_PlayZone_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Cash Giraffe",
        playableName: "Hole.IO",
        icon: "/AppIcons/hole-ioLogo.png",
        url: "/playableAds/HoleIO_CashGiraffe_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Grand Hotel Mania",
        playableName: "Prepare Street Food",
        icon: "/AppIcons/GrandHotelManiaIcon.png",
        url: "/playableAds/PBStreetFood_GrandHotelMania_MyGames_DogukanKaanBozkurt.html",
        isHighlighted: true,
    },
    {
        appName: "Just Games",
        playableName: "Mahjong With GameIcons",
        icon: "/AppIcons/MahjongIcon.png",
        url: "/playableAds/MahjongCarousel_JustGames_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Just Games",
        playableName: "Mahjong Original",
        icon: "/AppIcons/MahjongIcon.png",
        url: "/playableAds/MahjongOriginal_JustGames_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Just Games",
        playableName: "Reigns",
        icon: "/AppIcons/ReignsLogo.png",
        url: "/playableAds/StoryTeller_JustGames_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Game Perks",
        playableName: "Coffee Pack",
        icon: "/AppIcons/CoffeePackLogo.png",
        url: "/playableAds/CoffeePack_GamePerks_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Bonus Held",
        playableName: "Mini Metro",
        icon: "/AppIcons/Mini Metro.png",
        url: "/playableAds/MiniMetro_BonusHeld_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Cash Em All",
        playableName: "Color Block Jam",
        icon: "/AppIcons/ColorBlockJam.png",
        url: "/playableAds/ColorBlockJam_CashEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Cash Giraffe",
        playableName: "Valentines Goods Sort",
        icon: "/AppIcons/goodssort.png",
        url: "/playableAds/Valentines-GoodsSort_CashEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Cash Giraffe",
        playableName: "Travel Town",
        icon: "/AppIcons/TravelTown.png",
        url: "/playableAds/TravelTown_CashGiraffe_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Cash Giraffe",
        playableName: "Bus Out",
        icon: "/AppIcons/BusOut.png",
        url: "/playableAds/BusOut_CashGiraffe_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Mob Control",
        playableName: "Defeat Enemy Base",
        icon: "/AppIcons/MobControl.png",
        url: "/playableAds/MobControlUnityExport.html",
        isHighlighted: true,
    },
    {
        appName: "Cash Giraffe",
        playableName: "Goods Sort",
        icon: "/AppIcons/goodssort.png",
        url: "/playableAds/GoodsSorting_CashGiraffe_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Cash Em All",
        playableName: "Fruit Merge",
        icon: "/AppIcons/fruitmerge.png",
        url: "/playableAds/FruitMerge_CashEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Shoot Defender",
        playableName: "Evolving Weapons",
        icon: "/AppIcons/Shoot Defender.png",
        url: "/playableAds/ShootDefender_unityads.html",
        isHighlighted: true,
    },
    {
        appName: "Game Perks",
        playableName: "MoneyBunny Base GP",
        icon: "/AppIcons/Game Perks.png",
        url: "/playableAds/MoneyBunnyBaseGP_GamePerks_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Game Perks",
        playableName: "Gold Rush",
        icon: "/AppIcons/Game Perks.png",
        url: "/playableAds/GoldRush_GamePerks_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    // {
    //     appName:"Cash Granny",
    //     playableName:"Kill The Snake",
    //     icon: "/AppIcons/CashGrannyLogo.png",
    //     url:"/playableAds/KillTheSnake_CashGranny_Responsive_Playable_01_Unity_ALL.html",
    //     isHighlighted:false,
    // },
    {
        appName: "Test Em All",
        playableName: "Wood Nut & Bolt Puzzle",
        icon: "/AppIcons/woodsnut.png",
        url: "/playableAds/ScrewPuzzle_TestEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Money Turn",
        playableName: "KnifeHit",
        icon: "/AppIcons/knifehit.png",
        url: "/playableAds/KnifeHit_MoneyTurn_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Test Em All",
        playableName: "OneLine",
        icon: "/AppIcons/oneLineDrawing.png",
        url: "/playableAds/OneLine_TestEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Test Em All",
        playableName: "Monopoly",
        icon: "/AppIcons/monopoly.png",
        url: "/playableAds/Monopoly_TestEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Cash Cow",
        playableName: "Dice Merge",
        icon: "/AppIcons/dicemerge.png",
        url: "/playableAds/DiceMerge_CashCow_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Money Turn",
        playableName: "Tap Away",
        icon: "/AppIcons/tapaway.png",
        url: "/playableAds/TapAway_MoneyTurn_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "AppStation",
        playableName: "Traffic Escape!",
        icon: "/AppIcons/trafficescape.png",
        url: "/playableAds/TrafficEscape_Appstation_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Money Well",
        playableName: "Block Blast",
        icon: "/AppIcons/blockblast.png",
        url: "/playableAds/BlockBlast_MoneyWell_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Test Em All",
        playableName: "IEC-Water Sort",
        icon: "/AppIcons/watersort.png",
        url: "/playableAds/IEC-WaterSort_TestEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Test Em All",
        playableName: "Hexa Sort",
        icon: "/AppIcons/hexasort.png",
        url: "/playableAds/HexaSort_TestEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Cash Cow",
        playableName: "Feed The Cow",
        icon: "/AppIcons/Cash Cow.png",
        url: "/playableAds/FeedTheCow_CashCow_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Test Em All",
        playableName: "Match Factory",
        icon: "/AppIcons/matchfactory.png",
        url: "/playableAds/MatchFactory_TestEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Cash Giraffe",
        playableName: "Water Sort",
        icon: "/AppIcons/watersort.png",
        url: "/playableAds/WaterSort-EASY_CashGiraffe_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Test Em All",
        playableName: "Knot Words",
        icon: "/AppIcons/knotwords.png",
        url: "/playableAds/KnotWords_TestEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Scratch 4 Life",
        playableName: "Memorize And Scratch",
        icon: "/AppIcons/Scratch 4 Life.png",
        url: "/playableAds/MemorizeAndScratch_Scratch4Life_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "The Lucky Miner",
        playableName: "Gold Miner",
        icon: "/AppIcons/The Lucky Miner.png",
        url: "/playableAds/GoldMiner_TheLuckyMiner_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Money Bunny",
        playableName: "Boss Fight",
        icon: "/AppIcons/Money Bunny.png",
        url: "/playableAds/BearBossFight_MoneyBunny_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Money Bunny",
        playableName: "Upgrade Your Bunny",
        icon: "/AppIcons/Money Bunny.png",
        url: "/playableAds/BaseGameplay_MoneyBunny_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Cash Em All",
        playableName: "Parking Lot",
        icon: "/AppIcons/parkingjam.png",
        url: "/playableAds/ParkingLot_CashEmAll_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: true,
    },
    {
        appName: "Game Perks",
        playableName: "Cafe Clicker",
        icon: "/AppIcons/pizzaready.png",
        url: "/playableAds/CafeClicker_GamePerks_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "App Station",
        playableName: "Toon Blast",
        icon: "/AppIcons/toonblast.png",
        url: "/playableAds/ToonBlast_Appstation_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Money Well",
        playableName: "Carousel Gifs",
        icon: "/AppIcons/Money Well.png",
        url: "/playableAds/CarouselGifs_MoneyWell_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Cash Empire",
        playableName: "Shell Game",
        icon: "/AppIcons/Cash Empire.png",
        url: "/playableAds/ShellGame_CashEmpire_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "GameXpert",
        playableName: "Chicks Revenge",
        icon: "/AppIcons/GameXpert.png",
        url: "/playableAds/ChicksRevenge_GameXpert_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Money Slots",
        playableName: "Slot Machine",
        icon: "/AppIcons/Money Slots.png",
        url: "/playableAds/SlotMachine_MoneySlots_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Cashyy",
        playableName: "Planet Drive",
        icon: "/AppIcons/Cashyy.png",
        url: "/playableAds/PlanetDrive_Cashyy_Responsive_Playable_09_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Money Well",
        playableName: "Free Fall",
        icon: "/AppIcons/Money Well.png",
        url: "/playableAds/FreeFall_MoneyWell_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Cashyy",
        playableName: "Three Click Chest",
        icon: "/AppIcons/Cashyy.png",
        url: "/playableAds/ThreeClickChest_Cashyy_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Cash Alarm",
        playableName: "3D Pillow Throw",
        icon: "/AppIcons/Cash Alarm.png",
        isHighlighted: false,
        url: "/playableAds/3DPillowThrow_CashAlarm_Responsive_Playable_01_Unity_ALL.html",
    },
    {
        appName: "Carnival Clash",
        playableName: "Whack A Mole",
        icon: "/AppIcons/Carnival Clash.png",
        url: "/playableAds/BaseWhackAMole_CarnivalClash_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Cash Giraffe",
        playableName: "Match3",
        icon: "/AppIcons/Cash Giraffe.png",
        url: "/playableAds/Match3_CashGiraffe_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Rabbits VS Monsters",
        playableName: "Kill The Monsters",
        icon: "/AppIcons/Rabbits VS Monsters.png",
        url: "/playableAds/BaseGameplay_RvM_Responsive_Playable_01_Unity_ALL.html",
        isHighlighted: false,
    },
    {
        appName: "Raid Rush",
        playableName: "Re-Claim America",
        icon: "/AppIcons/Raid Rush.png",
        url: "/playableAds/ReClaimAmerica_DefenseLand_PLY_11.html",
        isHighlighted: false,
    },
    {
        appName: "Raid Rush",
        playableName: "Drag And Place Towers",
        icon: "/AppIcons/Raid Rush.png",
        url: "/playableAds/DragAndPlaceTowers_DefenseLand_PLY_09.html",
        isHighlighted: true,
    },
    {
        appName: "Gin Rummy",
        playableName: "Draw And Sort",
        icon: "/AppIcons/GinRummy.png",
        url: "/playableAds/DrawAndSort_GinnRummy_PLY_01.html",
        isHighlighted: true,
    },
    {
        appName: "Raid Rush",
        playableName: "FPS Tower Shooter",
        icon: "/AppIcons/Raid Rush.png",
        url: "/playableAds/FPSTowerShooter_DefenseLand_PLY_08.html",
        isHighlighted: false,
    },
    {
        appName: "Be My Guest",
        playableName: "AirBnb Idle",
        icon: "/AppIcons/Be My Guest.png",
        url: "/playableAds/AirbnbIdle_BeMyGuest_PLY_07.html",
        isHighlighted: false,
    },
    {
        appName: "Airport Master",
        playableName: "Seat Jam",
        icon: "/AppIcons/Airport Master.png",
        url: "/playableAds/SeatJam_AirportMaster_PLY_14.html",
        isHighlighted: true,
    },
    {
        appName: "Raid Rush",
        playableName: "Cross Camera",
        icon: "/AppIcons/Raid Rush.png",
        url: "/playableAds/CrossCamera_DefenseLand_PLY_05.html",
        isHighlighted: false,
    },
    {
        appName: "Fashion Famous",
        playableName: "Get Ready For Podium",
        icon: "/AppIcons/Fashion Famous.png",
        url: "/playableAds/GetReadyForPodium_FashionFamous_PLY_01.html",
        isHighlighted: false,
    },
    {
        appName: "Raid Rush",
        playableName: "Rushing Enemies",
        icon: "/AppIcons/Raid Rush.png",
        url: "/playableAds/RushingEnemies_DefenseLand_PLY_04.html",
        isHighlighted: false,
    },
    {
        appName: "Raid Rush",
        playableName: "Shoot Bombs",
        icon: "/AppIcons/Raid Rush.png",
        url: "/playableAds/ShootBombs_DefenseLand_PLY_02.html",
        isHighlighted: false,
    },
    {
        appName: "Be My Guest",
        playableName: "Place House Items",
        icon: "/AppIcons/Be My Guest.png",
        url: "/playableAds/PlaceHouseItems_BeMyGuest_PLY_05.html",
        isHighlighted: false,
    },
    {
        appName: "Model Agency",
        playableName: "Hire Model",
        icon: "/AppIcons/Model Agency.png",
        url: "/playableAds/HireModel_ModelAgent_PLY_03.html",
        isHighlighted: true,
    },
    {
        appName: "Raid Rush",
        playableName: "Call Enemy Waves",
        icon: "/AppIcons/Raid Rush.png",
        url: "/playableAds/CallEnemyWaves_DefenseLand_PLY_01.html",
        isHighlighted: true,
    },
    {
        appName: "Be My Guest",
        playableName: "Clean The House",
        icon: "/AppIcons/Be My Guest.png",
        url: "/playableAds/CleanTheHouse_BeMyGuest_PLY_03.html",
        isHighlighted: false,
    },
    {
        appName: "Fashion Famous",
        playableName: "Pick Costumes On Podium",
        icon: "/AppIcons/Fashion Famous.png",
        url: "/playableAds/PickCostumesOnPodium_FashionFamous_PLY_03.html",
        isHighlighted: false,
    },
    {
        appName: "Be My Guest",
        playableName: "Order From Amazon",
        icon: "/AppIcons/Be My Guest.png",
        url: "/playableAds/OrderFromAmazon_BeMyGuest_PLY_02.html",
        isHighlighted: true,
    },
    {
        appName: "Sling Plane",
        playableName: "Flight In City",
        icon: "/AppIcons/Sling Plane.png",
        url: "/playableAds/FlightInCity_SlingPlane_PLY_07.html",
        isHighlighted: false,
    },
    {
        appName: "Model Agency",
        playableName: "Create Your Top Model",
        icon: "/AppIcons/Model Agency.png",
        url: "/playableAds/CreateYourTopModel_ModelAgent_PLY_02.html",
        isHighlighted: false,
    },
    {
        appName: "Airport Master",
        playableName: "Passport Check In Island",
        icon: "/AppIcons/Airport Master.png",
        url: "/playableAds/PassportCheckInIslandAirport_AirportMaster_PLY_13.html",
        isHighlighted: false,
    },
    {
        appName: "My Chocolate Shop",
        playableName: "Cacao Factory",
        icon: "/AppIcons/My Chocolate Shop.png",
        url: "/playableAds/CacaoFactory_CacaoMaster_PLY_01.html",
        isHighlighted: false,
    },
    {
        appName: "Airport Master",
        playableName: "Scan Billie",
        icon: "/AppIcons/Airport Master.png",
        url: "/playableAds/ScanBillie_AirportMaster_PLY_07.html",
        isHighlighted: true,
    },
    {
        appName: "Airport Master",
        playableName: "Manage And Clean",
        icon: "/AppIcons/Airport Master.png",
        url: "/playableAds/ManageAndClean_AirportMaster_PLY_06.html",
        isHighlighted: true,
    },
    {
        appName: "Valet Master",
        playableName: "Manage Park Steps",
        icon: "/AppIcons/Valet Master.png",
        url: "/playableAds/ManageParkSteps_ValetMaster_PLY_06.html",
        isHighlighted: false,
    },
    {
        appName: "Model Agency",
        playableName: "Concept Gala",
        icon: "/AppIcons/Model Agency.png",
        url: "/playableAds/ConceptGALA_ModelAgent_PLY_01.html",
        isHighlighted: false,
    },
    {
        appName: "Airport Master",
        playableName: "Select Destination",
        icon: "/AppIcons/Airport Master.png",
        url: "/playableAds/SelectDestination_AirportMaster_PLY_10.html",
        isHighlighted: false,
    },
    {
        appName: "100 Mystery Buttons",
        playableName: "Water Prank",
        icon: "/AppIcons/100 Mystery Buttons.png",
        url: "/playableAds/WaterPrank_HundredMysteryButtons_PLY_02.html",
        isHighlighted: true,
    },
    {
        appName: "Airport Master",
        playableName: "Airport Island",
        icon: "/AppIcons/Airport Master.png",
        url: "/playableAds/AirportIsland_AirportMaster_PLY_05.html",
        isHighlighted: true,
    },
    {
        appName: "Airport Master",
        playableName: "Place Passengers",
        icon: "/AppIcons/Airport Master.png",
        url: "/playableAds/PlacePassengers_AirportMaster_PLY_04.html",
        isHighlighted: false,
    },
    {
        appName: "Destroy Master",
        playableName: "Destroy The Avocado",
        icon: "/AppIcons/Destroy Master.png",
        url: "/playableAds/KillTheAvacado_DestroyMaster_PLY_01.html",
        isHighlighted: false,
    },
    {
        appName: "Guess And Hit",
        playableName: "Guess The Country",
        icon: "/AppIcons/Guess And Hit.png",
        url: "/playableAds/GuessTheCountry_GuessAndHit_PLY_01.html",
        isHighlighted: false,
    },
    {
        appName: "Airport Master",
        playableName: "Carry Baggages",
        icon: "/AppIcons/Airport Master.png",
        url: "/playableAds/CarryBaggage_AirportMaster_PLY_03.html",
        isHighlighted: false,
    },
    {
        appName: "Bounce And Pop",
        playableName: "Hardest Level Ever",
        icon: "/AppIcons/Bounce And Pop.png",
        url: "/playableAds/PopBalloons_BounceAndPop_PLY_06.html",
        isHighlighted: false,
    },
    {
        appName: "Airport Master",
        playableName: "Passport Please",
        icon: "/AppIcons/Airport Master.png",
        url: "/playableAds/PassportPlease_AirportMaster_PLY_02.html",
        isHighlighted: false,
    },
    {
        appName: "Valet Master",
        playableName: "Cross Park",
        icon: "/AppIcons/Valet Master.png",
        url: "/playableAds/CrossPark_ValetMaster_PLY_05.html",
        isHighlighted: true,
    },
    {
        appName: "Airport Master",
        playableName: "Airport Manager",
        icon: "/AppIcons/Airport Master.png",
        url: "/playableAds/AirportManager_AirportMaster_PLY_01.html",
        isHighlighted: false,
    },
    {
        appName: "Clay Shop",
        playableName: "Customize Your Monster",
        icon: "/AppIcons/Clay Shop.png",
        url: "/playableAds/CustimizeYourMonster_ClayShop_3D_PLY_01.html",
        isHighlighted: false,
    },
    {
        appName: "Valet Master",
        playableName: "Repair The Car",
        icon: "/AppIcons/Valet Master.png",
        url: "/playableAds/RepairTheCar_ValetMaster_PLY_04.html",
        isHighlighted: false,
    },
    {
        appName: "Bounce And Pop",
        playableName: "Easy to Pop",
        icon: "/AppIcons/Bounce And Pop.png",
        url: "/playableAds/PopBalloons_BounceAndPop_PLY_01.html",
        isHighlighted: true,
    },
    {
        appName: "W Challenge",
        playableName: "Guess The Word",
        icon: "/AppIcons/W Challenge.png",
        url: "/playableAds/Drink_Worle_PLY_02.html",
        isHighlighted: false,
    },
    {
        appName: "Roll Merge 3D",
        playableName: "Throw And Merge",
        icon: "/AppIcons/Roll Merge 3D.png",
        url: "/playableAds/ThrowAndMerge_RollMerge_PLY_01.html",
        isHighlighted: true,
    },
    {
        appName: "Valet Master",
        playableName: "Drive The Van",
        icon: "/AppIcons/Valet Master.png",
        url: "/playableAds/DriveTheVan_ValetMaster_PLY_03.html",
        isHighlighted: false,
    },
    {
        appName: "Sling Plane",
        playableName: "Crush Control",
        icon: "/AppIcons/Sling Plane.png",
        url: "/playableAds/CrushControl_SlingPlane_PLY_05.html",
        isHighlighted: true,
    },
    {
        appName: "Muscle Land",
        playableName: "Calories And Energies",
        icon: "/AppIcons/Muscle Land.png",
        url: "/playableAds/CaloriesAndEnergies_MuscleLand_PLY_02.html",
        isHighlighted: false,
    },
    {
        appName: "Ball Brawl 3D",
        playableName: "World Cup Final",
        icon: "/AppIcons/Ball Brawl 3D - Soccer Cup.png",
        url: "/playableAds/3vs3WorldCup_BallBrawl3D_PLY_03.html",
        isHighlighted: false,
    },
    {
        appName: "Home Restoration",
        playableName: "Clear and Paint",
        icon: "/AppIcons/Home Restoration.png",
        url: "/playableAds/ClearAndPaintFloor_HomeRestoration_PLY_03.html",
        isHighlighted: true,
    },
    {
        appName: "Trading Master 3D",
        playableName: "IPhone Scam",
        icon: "/AppIcons/Trading Master 3D.png",
        url: "/playableAds/iPhoneScam_TradingMaster_PLY_01.html",
        isHighlighted: true,
    },
    {
        appName: "Mobu 2",
        playableName: "Pirate Mobu",
        icon: "/AppIcons/Mobu2.png",
        url: "/playableAds/Pirate_Mobu2_PLY_02.html",
        isHighlighted: false,
    },
    {
        appName: "Goal Party",
        playableName: "FranceVSArgentina",
        icon: "/AppIcons/Goal Party.png",
        url: "/playableAds/FranceVSArgentinaPenaly_GoalParty_PLY_03.html",
        isHighlighted: false,
    },
    {
        appName: "Valet Master",
        playableName: "Park Manager",
        icon: "/AppIcons/Valet Master.png",
        url: "/playableAds/ParkManager_ValetMaster_PLY_02.html",
        isHighlighted: false,
    },
    {
        appName: "Goal Party",
        playableName: "Penalties",
        icon: "/AppIcons/Goal Party.png",
        url: "/playableAds/Penalty_GoalParty_PLY_01.html",
        isHighlighted: true,
    },
    {
        appName: "Sling Plane",
        playableName: "Land On Airport",
        icon: "/AppIcons/Sling Plane.png",
        url: "/playableAds/LandOnAirport_SlingPlane_PLY_04.html",
        isHighlighted: false,
    },
    {
        appName: "100 Mystery Buttons",
        playableName: "Box Prank - Roblox",
        icon: "/AppIcons/100 Mystery Buttons.png",
        url: "/playableAds/RobloxLikePrank_HundredMysteryButtons_PLY_03.html",
        isHighlighted: false,
    },
    {
        appName: "Muscle Land",
        playableName: "Tap To Grow",
        icon: "/AppIcons/Muscle Land.png",
        url: "/playableAds/TapToGrow_MuscleLand_PLY_01.html",
        isHighlighted: false,
    },
    {
        appName: "Sling Plane",
        playableName: "Throw And Tunnel Ride",
        icon: "/AppIcons/Sling Plane.png",
        url: "/playableAds/ThrowAndTunnelRideUpgraded_SlingPlane_PLY_03.html",
        isHighlighted: false,
    },
];